window.PORTFOLIO_PROJECTS = [
  {
    id: "scifi-scene",
    title: "SCIFI SCENE",
    category: "Environment / Scene",
    kind: "scene",
    desktopSrc: "models/scifi-scene.glb",
    mobileSrc: "models/scifi-scene-mobile.glb",
    desktopSize: "15.5 MB",
    mobileSize: "46 KB",
    format: "GLB",
    mood: "Dystopian minimal",
    cardOrbit: "-30deg 68deg 240%",
    detailOrbit: "-28deg 68deg 320%",
    summary: "A dark industrial showcase piece presented as a realtime browser model for portfolio review.",
    description:
      "A dark sci-fi environment study built for interactive inspection. The web presentation focuses on scale, silhouette, and realtime readability across desktop and mobile."
  },
  {
    id: "ac-model",
    title: "AC MODEL",
    category: "Hard Surface / Asset",
    kind: "piece",
    desktopSrc: "models/ac.glb",
    mobileSrc: "models/ac-mobile.glb",
    desktopSize: "14.6 MB",
    mobileSize: "5.9 MB",
    format: "GLB",
    mood: "Industrial asset",
    cardOrbit: "-30deg 68deg 240%",
    detailOrbit: "-30deg 66deg 260%",
    summary: "A hard-surface asset added to the portfolio index with separate desktop and mobile-ready GLB files.",
    description:
      "A hard-surface asset focused on clean profile, bevel definition, and realtime presentation. This piece is set up with a lighter mobile file for safer phone inspection."
  },
  {
    id: "freedom-dorrito",
    title: "FREEDOM DORRITO",
    category: "Experimental / Form",
    kind: "piece",
    desktopSrc: "models/freedom-dorrito-ed.glb",
    mobileSrc: "models/freedom-dorrito-ed-mobile.glb",
    desktopSize: "43 KB",
    mobileSize: "43 KB",
    format: "GLB",
    mood: "Graphic form",
    cardOrbit: "-25deg 66deg 220%",
    detailOrbit: "-25deg 64deg 220%",
    summary: "A compact experimental form study built as a lightweight realtime GLB asset.",
    description:
      "A small-form model with a graphic silhouette and fast web load. It works well as a lightweight portfolio piece because the same asset can be inspected comfortably across devices."
  },
  {
    id: "x-model",
    title: "X MODEL",
    category: "Character / Figure",
    kind: "piece",
    desktopSrc: "models/x.glb",
    mobileSrc: "models/x-mobile.glb",
    desktopSize: "19.5 MB",
    mobileSize: "19.5 MB",
    format: "GLB",
    mood: "Figure study",
    cardOrbit: "-25deg 66deg 280%",
    detailOrbit: "-25deg 64deg 320%",
    summary: "A heavier figure model prepared for dedicated realtime inspection.",
    description:
      "A larger figure model with more geometry weight than the other assets. The detail view loads it as a single focused inspection experience instead of stacking it with every other model on mobile."
  },
  {
    id: "hailmary",
    title: "HAIL MARY",
    category: "Sci-Fi / Scene",
    kind: "scene",
    sceneManifest: "models/hailmary/manifest.json",
    previewImage: "models/hailmary/thumbnail.png",
    desktopSrc: "models/hailmary/parts/mainbbase.glb",
    mobileSrc: "models/hailmary/parts/mainbbase.glb",
    desktopSize: "48.7 MB parts",
    mobileSize: "48.7 MB parts",
    format: "GLB parts",
    mood: "Propulsion assembly",
    cardOrbit: "-35deg 66deg 320%",
    detailOrbit: "-35deg 64deg 340%",
    summary: "A multi-object sci-fi assembly extracted into inspectable scene parts with saved transforms.",
    description:
      "A heavier Hail Mary scene rebuilt from separate GLB parts. The scene viewer keeps the full assembly available for selection, isolation, clay inspection, and exploded-view review."
  },
  {
    id: "spaceship",
    title: "SPACESHIP",
    category: "Vehicle / Spacecraft",
    kind: "piece",
    desktopSrc: "models/spaceship.glb",
    mobileSrc: "models/spaceship-mobile.glb",
    desktopSize: "32.9 MB",
    mobileSize: "32.9 MB",
    format: "GLB",
    mood: "Sci-fi vehicle",
    cardOrbit: "-35deg 66deg 300%",
    detailOrbit: "-35deg 64deg 340%",
    summary: "A larger sci-fi vehicle model presented as a dedicated inspection asset.",
    description:
      "A heavier spacecraft model built for full-screen inspection. Because this file is geometry-heavy rather than texture-heavy, the detail page presents it as a focused model view instead of loading it into the mobile gallery."
  },
  {
    id: "rockys-ship",
    title: "ROCKY'S SHIP",
    category: "Vehicle / Scene",
    kind: "scene",
    sceneManifest: "models/rockys-ship/manifest.json",
    previewImage: "models/rockys-ship/thumbnail.png",
    desktopSrc: "models/rockys-ship/parts/centerbody.glb",
    mobileSrc: "models/rockys-ship/parts/centerbody.glb",
    desktopSize: "942 KB parts",
    mobileSize: "942 KB parts",
    format: "GLB parts",
    mood: "Needle ship assembly",
    cardOrbit: "-35deg 66deg 320%",
    detailOrbit: "-35deg 64deg 340%",
    summary: "A lightweight multi-part ship scene rebuilt for full assembly inspection.",
    description:
      "A compact ship scene extracted into loops, body sections, and needle parts. The scene viewer presents the full assembled vehicle with selection, isolation, clay inspection, and exploded-view controls."
  },
  {
    id: "citadel",
    title: "CITADEL",
    category: "Environment / Structure",
    kind: "scene",
    desktopSrc: "models/citadel.glb",
    mobileSrc: "models/citadel-mobile.glb",
    desktopSize: "4.5 MB",
    mobileSize: "4.5 MB",
    format: "GLB",
    mood: "Fortress study",
    cardOrbit: "-30deg 66deg 260%",
    detailOrbit: "-30deg 64deg 300%",
    summary: "A midweight fortress-style structure model prepared for realtime inspection.",
    description:
      "A structural sci-fi study with enough detail for close inspection while staying light enough for web delivery. The detail page keeps the model centered as a dedicated realtime asset."
  },
  {
    id: "deathsphere",
    title: "DEATHSPHERE",
    category: "Hard Surface / Artifact",
    kind: "piece",
    desktopSrc: "models/deathsphere.glb",
    mobileSrc: "models/deathsphere-mobile.glb",
    desktopSize: "86.9 MB",
    mobileSize: "4.2 MB",
    format: "GLB",
    mood: "Dark industrial",
    cardOrbit: "-35deg 66deg 300%",
    detailOrbit: "-35deg 64deg 340%",
    summary: "A large hard-surface sphere asset with a compressed mobile inspection file.",
    description:
      "A heavy industrial sphere model with embedded metal materials. The desktop detail view keeps the full-resolution GLB available, while the gallery and mobile detail view use a compressed realtime version for smoother loading."
  },
  {
    id: "gate-scene",
    title: "GATE SCENE",
    category: "Environment / Scene",
    kind: "scene",
    sceneManifest: "models/gate-scene/manifest.json",
    desktopSrc: "models/gate-scene/parts/cover-01.glb",
    mobileSrc: "models/gate-scene/parts/cover-01.glb",
    desktopSize: "42.7 MB parts",
    mobileSize: "42.7 MB parts",
    format: "GLB parts",
    mood: "Inspectable assembly",
    cardOrbit: "-35deg 66deg 320%",
    detailOrbit: "-35deg 64deg 340%",
    summary: "A multi-object gate assembly rebuilt from separate GLB parts with saved scene transforms.",
    description:
      "A manifest-driven scene assembled from individual extracted GLB parts. This is the first scene built for object selection, isolated inspection, and exploded-view interaction."
  }
];
